In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('Soil Project 2020/CropData.csv')

In [4]:
df

District      Village    pH     EC    OC        N         P       K  \
0        Shirala     Ambewadi  6.70  0.240  0.67  262.400   30.0000  224.40   
1        Shirala     Ambewadi  6.70  0.240  0.67  262.400   30.0000  224.40   
2        Shirala     Ambewadi  6.70  0.240  0.67  262.400   30.0000  224.40   
3        Shirala     Ambewadi  6.70  0.240  0.67  262.400   30.0000  224.40   
4        Shirala     Ambewadi  6.70  0.240  0.67  262.400   30.0000  224.40   
...          ...          ...   ...    ...   ...      ...       ...     ...   
179232  Khamgaon    Garadgaon  8.39  0.840  0.14  144.260  135.5000  586.43   
179233    Jamner  Londhri Kh.  7.80  0.390  0.33  153.664    4.0524  458.30   
179234    Mukhed       Eklara  7.39  0.120  0.25  163.000   45.1000  255.00   
179235   Shirala     Karamale  6.54  0.430  0.49  109.700   42.9000  455.40   
179236      Wani  Kalmana Bk.  7.70  0.182  0.37  259.000   19.2000  291.50   

            S    Zn    Fe    Cu    Mn     B         Soil_type    Soil_Quality  \
0       10.90  0.74  5.60  1.77  5.51  0.77           Neutral    Fertile Soil   
1       10.90  0.74  5.60  1.77  5.51  0.77           Neutral    Fertile Soil   
2       10.90  0.74  5.60  1.77  5.51  0.77           Neutral    Fertile Soil   
3       10.90  0.74  5.60  1.77  5.51  0.77           Neutral    Fertile Soil   
4       10.90  0.74  5.60  1.77  5.51  0.77           Neutral    Fertile Soil   
...       ...   ...   ...   ...   ...   ...               ...             ...   
179232   6.22  0.86  1.04  0.85  8.25  0.51  Slighty alkaline  Unfertile Soil   
179233  13.30  0.87  6.60  0.43  6.60  0.50           Neutral  Unfertile Soil   
179234  21.47  0.61  3.48  0.62  3.03  0.34           Neutral    Fertile Soil   
179235  17.20  0.45  4.57  0.92  5.31  0.65           Neutral    Fertile Soil   
179236   4.98  0.29  4.62  0.28  5.27  0.52           Neutral  Unfertile Soil   

             Crop  
0       GroundNut  
1       GroundNut  
2       GroundNut  
3       GroundNut  
4       GroundNut  
...           ...  
179232    No Crop  
179233    No Crop  
179234    No Crop  
179235    No Crop  
179236    No Crop  

[179237 rows x 17 columns]

In [5]:
df1=df.copy() 
s=df1[df1.Crop == 'Sugarcane' ] 
s=s.sample(frac=0.18,random_state=2021)
c=df1[df1.Crop == 'Cotton' ] 
c=c.sample(frac=0.033,random_state=2021)
g=df1[df1.Crop == 'GroundNut' ] 
g=g.sample(frac=0.49,random_state=2021)
so=df1[df1.Crop == 'Soybean' ] 
so=so.sample(frac=0.077,random_state=2021)
n=df1[df1.Crop == 'No Crop' ] 
n=n.sample(frac=0.095,random_state=2021)
w=df1[df1.Crop == 'Wheat' ]
df=pd.concat([c,s,so,g,w,n])
df.shape

(16807, 17)

In [6]:
x=df.iloc[:,2:14]
y=df.iloc[:,16]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size = 0.3,random_state=2021,stratify=y)

In [8]:
from sklearn.ensemble import RandomForestClassifier
rm=RandomForestClassifier(max_features=2,random_state=2021)
rm.fit(X_train,y_train)
predx=rm.predict(X_test)

In [9]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
result=confusion_matrix(y_test,predx)
print("confusion matrix\n",result)
result1=classification_report(y_test,predx)
print("Classification report\n",result1)
result2=accuracy_score(y_test,predx)
print("Accuracy_score\n",result2)

confusion matrix
 [[746   7  23  48  23   8]
 [  4 790   0   0   2   0]
 [ 26   9 899  69  13   4]
 [ 32  12  64 676   4   7]
 [ 22   8   4   8 746   7]
 [  0   0   7   4   3 768]]
Classification report
               precision    recall  f1-score   support

      Cotton       0.90      0.87      0.89       855
   GroundNut       0.96      0.99      0.97       796
     No Crop       0.90      0.88      0.89      1020
     Soybean       0.84      0.85      0.85       795
   Sugarcane       0.94      0.94      0.94       795
       Wheat       0.97      0.98      0.97       782

    accuracy                           0.92      5043
   macro avg       0.92      0.92      0.92      5043
weighted avg       0.92      0.92      0.92      5043

Accuracy_score
 0.9171128296648821


In [10]:
import pickle

In [11]:
pickle_out = open("classifier.pkl","wb")
pickle.dump(rm,pickle_out)
pickle_out.close()

In [12]:
X_test

pH     EC    OC        N         P       K         S    Zn    Fe  \
174393  7.48  0.199  0.58  234.080   16.7100  164.50   6.30000  1.29  4.27   
92199   7.37  0.520  0.62  240.840  143.0000  295.72   3.56000  1.14  0.84   
73391   7.92  0.267  0.45  315.000   35.6000  267.80   6.48000  0.44  5.98   
90246   7.90  0.510  0.26  179.000   15.4800  369.60   3.48000  0.86  1.64   
129538  7.90  0.690  0.53  331.000   75.0000  264.80   5.69000  0.35  1.22   
...      ...    ...   ...      ...       ...     ...       ...   ...   ...   
76679   7.57  0.134  0.39  273.000   26.2000  227.80  18.20000  0.67  2.45   
72046   7.30  0.210  0.73  223.500   40.7100  156.10   6.00000  1.09  5.30   
1232    6.56  0.060  0.74  175.600   36.4000  442.40   5.18000  0.29  3.85   
89269   7.94  0.630  0.66  229.550  121.0000  332.23   2.04000  0.98  0.63   
76110   7.62  0.170  0.54  338.688   23.4192  476.00  20.93856  0.79  3.26   

           Cu     Mn       B  
174393  2.400  13.76  1.0400  
92199   1.780  10.56  0.7700  
73391   0.470   4.78  0.2900  
90246   2.100   5.56  0.6000  
129538  1.100   6.11  0.5000  
...       ...    ...     ...  
76679   0.470   7.28  0.5200  
72046   0.711   0.58  0.8900  
1232    1.750   6.60  0.0640  
89269   1.250   3.37  0.7600  
76110   0.530  14.58  0.7665  

[5043 rows x 12 columns]

In [14]:
#s=np.array()
a=rm.predict([[7.48,0.199,0.58,234.08,16.71,164.50,6.3,1.29,4.27,2.4,13.76,1.04]])

In [15]:
a

array(['No Crop'], dtype=object)

In [16]:
a[0]

'No Crop'